import Link from "next/link";
import { notFound } from "next/navigation";
import type { Metadata } from "next";
import { MDXRemote } from "next-mdx-remote/rsc";
import remarkGfm from "remark-gfm";
import {
  getAllPosts,
  getPost,
  getPostBody,
  getPostSlugs,
  getAuthor,
  getCategory,
  heroCardSrc,
  heroImageExists,
} from "@/lib/content";
import { mdxComponents } from "@/components/mdx-components";

// Pre-render all article URLs at build time (static export).
export async function generateStaticParams() {
  return getPostSlugs().map((slug) => ({ slug }));
}

interface PageProps {
  params: Promise<{ slug: string }>;
}

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { slug } = await params;
  const post = getPost(slug);
  if (!post) return {};
  const url = `https://pettranslator.ai/blog/${slug}`;
  const author = getAuthor(post.author);
  // OG image: Next.js auto-injects /blog/[slug]/opengraph-image.png
  // (generated by ./opengraph-image.tsx at build time) whenever this
  // generateMetadata call OMITS openGraph.images. So we deliberately
  // do NOT set images here for slugs that have an opengraph-image
  // sibling — that's every published slug, by design.
  //
  // Articles whose hero WebP file doesn't exist on disk still get an
  // OG image generated (the layout falls back to no photo panel) — so
  // we always defer to the auto-injected one. The heroImageExists()
  // helper used to gate this is now only used for the in-article
  // <img> render below.
  // Trim the social-card description to 125 chars. Why this threshold:
  //   - Discord, Slack, Messages truncate previews at ~125 on mobile —
  //     anything longer shows visible "…" truncation that looks like
  //     content was lost mid-thought.
  //   - Twitter shows ~200, Facebook ~300, Google snippet ~155 — all
  //     comfortably above 125 so we don't waste space there either.
  //   - Going below 120 would leave us showing fragments instead of
  //     complete thoughts. 125 is the sweet spot.
  //
  // The full post.description still goes in <meta name="description">
  // for SEO so Google's SERP sees the long form.
  const OG_DESC_MAX = 125;
  const ogDescription =
    post.description.length > OG_DESC_MAX
      ? post.description
          .slice(0, OG_DESC_MAX - 1)
          .replace(/[\s,;:.!?\-—–]+$/, "")
        + "…"
      : post.description;

  return {
    title: post.title,
    description: post.description,
    alternates: { canonical: url },
    openGraph: {
      title: post.title,
      description: ogDescription,
      url,
      type: "article",
      // siteName must be redeclared on every page that defines its own
      // openGraph — Next.js metadata replaces the parent openGraph
      // object wholesale rather than deep-merging, so the root layout's
      // siteName wouldn't show on article pages without this line.
      // Discord uses og:site_name as the bold header above the card.
      siteName: "PetTranslator.ai",
      publishedTime: post.publishedAt,
      modifiedTime: post.updatedAt,
      // Use the author's human-readable name (not the slug) so AI search
      // engines, RSS readers, and OG-card consumers attribute correctly.
      authors: [author?.name ?? post.author],
      tags: post.tags,
      // Intentionally no images[] — let the file-based opengraph-image
      // convention populate it. Twitter card pulls from the same source.
    },
    twitter: { card: "summary_large_image", description: ogDescription },
  };
}

export default async function ArticlePage({ params }: PageProps) {
  const { slug } = await params;
  const post = getPost(slug);
  if (!post) notFound();

  // Read the raw MDX body (frontmatter stripped by gray-matter) and render
  // it via next-mdx-remote/rsc. This sidesteps Turbopack's inability to
  // serialize remark-frontmatter as a loader plugin — instead, we compile
  // the MDX on the server at build time from a string we control.
  const body = getPostBody(slug);
  if (!body) notFound();

  const author = getAuthor(post.author);
  const category = getCategory(post.category);

  // Sibling articles in the same category — used in related-articles below.
  const related = getAllPosts()
    .filter((p) => p.category === post.category && p.slug !== slug)
    .slice(0, 4);

  const url = `https://pettranslator.ai/blog/${slug}`;

  const heroLive = heroImageExists(post.heroImage);
  const heroCard = heroCardSrc(post.heroImage);
  const heroSrcSet =
    heroCard && heroCard !== post.heroImage
      ? `${heroCard} 600w, ${post.heroImage} 1376w`
      : undefined;

  return (
    <>
      {/* Article + BreadcrumbList JSON-LD per page */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@graph": [
              {
                "@type": "Article",
                "@id": `${url}#article`,
                headline: post.title,
                description: post.description,
                datePublished: post.publishedAt,
                dateModified: post.updatedAt,
                author: author
                  ? {
                      "@type": "Person",
                      name: author.name,
                      url: `https://pettranslator.ai/blog/author/${author.slug}`,
                    }
                  : undefined,
                publisher: { "@id": "https://pettranslator.ai/#organization" },
                // Article schema image — prefer the article's own hero
                // when shipped; fall back to the sitewide /og.png so this
                // never points at a 404 during the period before hero
                // images ship.
                image: heroImageExists(post.heroImage)
                  ? `https://pettranslator.ai${post.heroImage}`
                  : "https://pettranslator.ai/og.png",
                mainEntityOfPage: url,
                articleSection: category?.name,
                keywords: post.tags.join(", "),
              },
              {
                "@type": "BreadcrumbList",
                itemListElement: [
                  {
                    "@type": "ListItem",
                    position: 1,
                    name: "Home",
                    item: "https://pettranslator.ai/",
                  },
                  {
                    "@type": "ListItem",
                    position: 2,
                    name: "Blog",
                    item: "https://pettranslator.ai/blog",
                  },
                  category && {
                    "@type": "ListItem",
                    position: 3,
                    name: category.name,
                    item: `https://pettranslator.ai/blog/category/${category.slug}`,
                  },
                  {
                    "@type": "ListItem",
                    position: category ? 4 : 3,
                    name: post.title,
                  },
                ].filter(Boolean),
              },
            ],
          }),
        }}
      />

      <main className="mx-auto max-w-3xl px-6 py-12 sm:py-16">
        {/* Breadcrumb */}
        <nav className="label mb-6 flex gap-2 flex-wrap text-slate-soft">
          <Link href="/blog" className="hover:text-terra">Blog</Link>
          <span>/</span>
          {category && (
            <>
              <Link
                href={`/blog/category/${category.slug}`}
                className="hover:text-terra"
              >
                {category.name}
              </Link>
              <span>/</span>
            </>
          )}
          <span className="text-slate">{post.title.split(":")[0]}</span>
        </nav>

        <header className="mb-12">
          <h1 className="mb-5">{post.title}</h1>
          <p className="text-slate text-lg leading-relaxed max-w-prose mb-6">
            {post.description}
          </p>
          {/* Hero image rendered here, ABOVE the byline, when the file
              has shipped. Width = container max-w-3xl (~768px) so the
              browser only needs the resized variant; the source is already
              within budget at 1376px. */}
          {heroLive && (
            <figure className="-mx-6 sm:mx-0 sm:rounded-3xl overflow-hidden mb-8">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={post.heroImage}
                srcSet={heroSrcSet}
                sizes="(max-width: 640px) 100vw, 768px"
                alt={post.heroAlt}
                width={1376}
                height={768}
                loading="eager"
                fetchPriority="high"
                decoding="async"
                className="w-full h-auto"
              />
            </figure>
          )}
          <div className="flex flex-wrap gap-x-5 gap-y-1 text-xs font-mono text-slate-soft">
            {author && (
              <Link
                href={`/blog/author/${author.slug}`}
                className="hover:text-terra"
              >
                By {author.name}
              </Link>
            )}
            <span>
              {new Date(post.publishedAt).toLocaleDateString("en-US", {
                month: "long",
                day: "numeric",
                year: "numeric",
              })}
            </span>
            <span>{post.readingTime} read</span>
          </div>
        </header>

        {post.tldr && (
          <aside className="mx-auto mb-10 max-w-[38rem] rounded-2xl border border-rule bg-paper-light px-5 py-4">
            <p className="label mb-2 text-terra">TL;DR</p>
            <p className="m-0 leading-relaxed text-ink">{post.tldr}</p>
          </aside>
        )}

        {/* The MDX body — compiled at build time from the gray-matter-
            stripped body string. Custom components (Callout, TryItCTA)
            wired via the components prop. */}
        <article className="prose-editorial">
          <MDXRemote
            source={body}
            components={mdxComponents}
            options={{ mdxOptions: { remarkPlugins: [remarkGfm] } }}
          />
        </article>

        {/* Tags */}
        {post.tags.length > 0 && (
          <div className="mt-12 pt-6 border-t border-rule flex flex-wrap gap-2">
            <span className="label">Tags</span>
            {post.tags.map((tag) => (
              <Link
                key={tag}
                href={`/blog/tag/${tag}`}
                className="text-xs font-mono text-slate hover:text-terra"
              >
                #{tag}
              </Link>
            ))}
          </div>
        )}

        {/* Related articles in the same category */}
        {related.length > 0 && (
          <section className="mt-16 pt-8 border-t border-rule">
            <p className="label mb-5">From our {category?.name ?? "journal"}</p>
            <ul className="grid sm:grid-cols-2 gap-x-6 gap-y-5">
              {related.map((r) => (
                <li key={r.slug}>
                  <Link
                    href={`/blog/${r.slug}`}
                    className="group block"
                  >
                    <p className="label mb-1">{r.readingTime}</p>
                    <h4 className="font-serif text-base leading-snug group-hover:text-terra transition">
                      {r.title}
                    </h4>
                  </Link>
                </li>
              ))}
            </ul>
          </section>
        )}
      </main>
    </>
  );
}
